version: '3.7'

services:
    web:
        build: .
        command: gunicorn picturator_project.wsgi -b 0.0.0.0:8000
        environment:
            - SECRET_KEY=pu)+y_2$$n9^jhn7x2p2dn%w()!9r)dlu4c-*(p#o0i&r%*@2ai
            - DEBUG=1
            - STRIPE_TEST_PUBLISHABLE_KEY=<pk_test_aNKIAK4xfaUUG8w1Jmaz1lmN00hfb36tCp>
            - STRIPE_TEST_SECRET_KEY=<sk_test_6SmJlrvdhAMZPEXPQoN1fnXk00k1QvIowc>
            - ENVIRONMENT=development
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_DB: picturator
            POSTGRES_USER: picturator
            POSTGRES_PASSWORD: picturator
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: